[package]
name = "sdkman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.2" }
reqwest = { version = "0.11.9" }
tokio = { version = "1.17.0", features = ["full"] }